/**
 * This class is generated by jOOQ
 */
package jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_542B1C4D_5EE1_488B_9EBD_080C1E76B8B7</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_542B1C4D_5EE1_488B_9EBD_080C1E76B8B7 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_542B1C4D_5EE1_488B_9EBD_080C1E76B8B7", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
